version: "3.8"

services:
  ecm-mnr-be:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3001:3000
        #    volumes:
        #      - /root/gtos-backend:/app
    restart: always
