-- CreateTable
CREATE TABLE "dt_container" (
    "id" BIGSERIAL NOT NULL,
    "id_tos" VARCHAR(200),
    "id_cont" VARCHAR(50),
    "id_cont_tos" VARCHAR(200),
    "vessel_key" VARCHAR(100) NOT NULL,
    "vessel_imvoy" VARCHAR(20),
    "vessel_exvoy" VARCHAR(20),
    "eta" TIMESTAMPTZ(3),
    "etb" TIMESTAMPTZ(3),
    "etd" TIMESTAMPTZ(3),
    "barge_in_key" VARCHAR(100),
    "barge_out_key" VARCHAR(100),
    "delivery_order" VARCHAR(100),
    "bl_no" VARCHAR(100),
    "booking_no" VARCHAR(100),
    "house_bill_no" VARCHAR(100),
    "container_no" VARCHAR(20) NOT NULL,
    "class_code" VARCHAR(50) NOT NULL,
    "operation_code" VARCHAR(50) NOT NULL,
    "fe" VARCHAR(10) NOT NULL,
    "container_status_code" VARCHAR(50) NOT NULL,
    "cargo_type_code" VARCHAR(50) NOT NULL,
    "commodity" TEXT,
    "local_size_type" VARCHAR(10) NOT NULL,
    "iso_size_type" VARCHAR(10) NOT NULL,
    "is_local_foreign" VARCHAR(5) NOT NULL,
    "job_mode_code_in" VARCHAR(50),
    "method_code_in" VARCHAR(50),
    "date_in" TIMESTAMPTZ(3),
    "job_mode_code_out" VARCHAR(50),
    "method_code_out" VARCHAR(50),
    "date_out" TIMESTAMPTZ(3),
    "require_survey_date" TIMESTAMPTZ(3),
    "repair_move_date" TIMESTAMPTZ(3),
    "eir_in_no" VARCHAR(50),
    "eir_out_no" VARCHAR(50),
    "stuff_no" VARCHAR(50),
    "unstuff_no" VARCHAR(50),
    "service_no" VARCHAR(50),
    "draft_no" VARCHAR(50),
    "invoice_no" VARCHAR(50),
    "zone_code" VARCHAR(50),
    "yard_code" VARCHAR(50),
    "line_code" VARCHAR(50),
    "block" VARCHAR(5),
    "bay" VARCHAR(5),
    "row" VARCHAR(5),
    "tier" VARCHAR(5),
    "area" VARCHAR(5),
    "vgm" BOOLEAN NOT NULL DEFAULT false,
    "mc_weight" DECIMAL(18,2),
    "tare_weight" DECIMAL(18,2),
    "max_gross_weight" DECIMAL(18,2),
    "seal_no" VARCHAR(50),
    "seal_no1" VARCHAR(50),
    "seal_no2" VARCHAR(50),
    "pol" VARCHAR(5),
    "pod" VARCHAR(5),
    "fpod" VARCHAR(5),
    "transit_code" VARCHAR(50),
    "transit_port" VARCHAR(5),
    "temperature" VARCHAR(10),
    "vent" DECIMAL(10,2),
    "vent_unit" VARCHAR(10),
    "cus_hold" BOOLEAN NOT NULL DEFAULT false,
    "ter_hold" BOOLEAN NOT NULL DEFAULT false,
    "ter_hold_reason" TEXT,
    "is_special_warning" BOOLEAN NOT NULL DEFAULT false,
    "special_warning" TEXT,
    "condition_code" VARCHAR(50),
    "classify_code" VARCHAR(50),
    "condition_machine_code" VARCHAR(50),
    "is_truck_barge" VARCHAR(1),
    "truck_no" VARCHAR(10),
    "romooc_no" VARCHAR(10),
    "is_bundled" INTEGER DEFAULT 0,
    "container_no_master" VARCHAR(20),
    "note_cont" TEXT,
    "note_damage" TEXT,
    "note_special_handling" TEXT,
    "note" TEXT,
    "created_date" TIMESTAMPTZ(3) DEFAULT CURRENT_TIMESTAMP,
    "created_by" VARCHAR(36) NOT NULL,
    "modified_date" TIMESTAMPTZ(3),
    "modified_by" VARCHAR(36),

    CONSTRAINT "dt_container_pkey" PRIMARY KEY ("id")
);
