import { Command, CommandProps } from '@libs/ddd';
import { Prisma } from '@prisma/client';

export class UpdateContainerCommand extends Command {
  readonly containerId: bigint;
  readonly idTos?: string;
  readonly idCont?: string;
  readonly idContTos?: string;
  readonly vesselKey?: string;
  readonly vesselImvoy?: string;
  readonly vesselExvoy?: string;
  readonly eta?: Date;
  readonly etb?: Date;
  readonly etd?: Date;
  readonly bargeInKey?: string;
  readonly bargeOutKey?: string;
  readonly deliveryOrder?: string;
  readonly blNo?: string;
  readonly bookingNo?: string;
  readonly houseBillNo?: string;
  readonly containerNo?: string;
  readonly classCode?: string;
  readonly operationCode?: string;
  readonly fe?: string;
  readonly containerStatusCode?: string;
  readonly cargoTypeCode?: string;
  readonly commodity?: string;
  readonly localSizeType?: string;
  readonly isoSizeType?: string;
  readonly isLocalForeign?: string;
  readonly jobModeCodeIn?: string;
  readonly methodCodeIn?: string;
  readonly dateIn?: Date;
  readonly jobModeCodeOut?: string;
  readonly methodCodeOut?: string;
  readonly dateOut?: Date;
  readonly requireSurveyDate?: Date;
  readonly repairMoveDate?: Date;
  readonly eirInNo?: string;
  readonly eirOutNo?: string;
  readonly stuffNo?: string;
  readonly unstuffNo?: string;
  readonly serviceNo?: string;
  readonly draftNo?: string;
  readonly invoiceNo?: string;
  readonly zoneCode?: string;
  readonly yardCode?: string;
  readonly lineCode?: string;
  readonly block?: string;
  readonly bay?: string;
  readonly row?: string;
  readonly tier?: string;
  readonly area?: string;
  readonly vgm: boolean;
  readonly mcWeight?: Prisma.Decimal;
  readonly tareWeight?: Prisma.Decimal;
  readonly maxGrossWeight?: Prisma.Decimal;
  readonly sealNo?: string;
  readonly sealNo1?: string;
  readonly sealNo2?: string;
  readonly pol?: string;
  readonly pod?: string;
  readonly fpod?: string;
  readonly transitCode?: string;
  readonly transitPort?: string;
  readonly temperature?: string;
  readonly vent?: Prisma.Decimal;
  readonly ventUnit?: string;
  readonly cusHold?: boolean;
  readonly terHold?: boolean;
  readonly terHoldReason?: string;
  readonly isSpecialWarning?: boolean;
  readonly specialWarning?: string;
  readonly conditionCode?: string;
  readonly classifyCode?: string;
  readonly conditionMachineCode?: string;
  readonly isTruckBarge?: string;
  readonly truckNo?: string;
  readonly romoocNo?: string;
  readonly isBundled?: number;
  readonly containerNoMaster?: string;
  readonly noteCont?: string;
  readonly noteDamge?: string;
  readonly noteSpecialHandling?: string;
  readonly note?: string;
  readonly updatedBy: string;

  constructor(props: CommandProps<UpdateContainerCommand>) {
    super(props);
    Object.assign(this, props);
  }
}
